name: compile-release
on:
  push:
    # GitHub Releases requires a tag
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: workbench
        spec: EasyMCP2221-workbench.spec

#    - uses: actions/upload-artifact@v3
#      with:
#        name: EasyMCP2221-workbench
#        path: dist/windows/EasyMCP2221-workbench.exe

    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: workbench/dist/windows/EasyMCP2221-workbench.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
